# Generated by Django 2.0 on 2018-02-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamestate',
            fields=[
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gamestate', serialize=False, to='core.Game')),
                ('data', models.TextField()),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gamestate', to='core.Player')),
            ],
        ),
    ]
