# Generated by Django 2.0 on 2018-02-20 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180220_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='times_bought',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 10, 10, 9, 829909)),
        ),
    ]
