# Generated by Django 2.0 on 2018-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180216_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate',
            old_name='game',
            new_name='stateGame',
        ),
        migrations.RenameField(
            model_name='gamestate',
            old_name='player',
            new_name='statePlayer',
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
