# Generated by Django 2.0 on 2018-02-15 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_highscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player'),
        ),
    ]
