# Generated by Django 2.0 on 2018-02-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180216_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate',
            old_name='data',
            new_name='gamestate',
        ),
    ]
