# Generated by Django 2.0 on 2018-02-18 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180216_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 18, 12, 42, 59, 774320)),
        ),
    ]
